# Generated by Django 6.1.1 on 2026-10-02 18:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('saspay', 'SASPAY'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Méthode')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('rejected', 'Rejeté'), ('expired', 'Expiré')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='USD', editable=False, max_length=3, verbose_name='Devise')),
                ('internal_reference', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='Référence interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmé le')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaspayTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saspay_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID transaction SASPAY')),
                ('saspay_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence SASPAY')),
                ('raw_request', models.JSONField(blank=True, default=dict, verbose_name='Requête brute')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='Réponse brute')),
                ('signature_verified', models.BooleanField(default=False, verbose_name='Signature vérifiée')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Vérifié le')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saspay', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Transaction SASPAY',
                'verbose_name_plural': 'Transactions SASPAY',
            },
        ),
        migrations.CreateModel(
            name='WhatsappProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_file', models.FileField(help_text="Capture d'écran ou PDF du paiement.", upload_to='proofs/%Y/%m/', verbose_name='Fichier de preuve')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée'), ('rejected', 'Rejetée'), ('new_proof_requested', 'Nouvelle preuve demandée')], db_index=True, default='pending', max_length=30, verbose_name='Statut')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_proof', to='payments.payment', verbose_name='Paiement')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_proofs', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Preuve WhatsApp',
                'verbose_name_plural': 'Preuves WhatsApp',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reservation', 'status'], name='payments_pa_reserva_a9955b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method', 'status'], name='payments_pa_method_c0b72b_idx'),
        ),
    ]
