# Generated by Django 6.1.1 on 2026-10-02 14:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, help_text='Format : BGA-2026-XXXXXXX', max_length=20, unique=True, verbose_name='Référence')),
                ('seats', models.PositiveIntegerField(default=1, help_text='Entre 1 et 5 places par réservation.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nombre de places')),
                ('status', models.CharField(choices=[('created', 'Créée'), ('payment_pending', 'Paiement en attente'), ('payment_confirmed', 'Paiement confirmé'), ('confirmed', 'Confirmée'), ('ticket_generated', 'Billet généré'), ('present', 'Présent'), ('cancelled', 'Annulée')], db_index=True, default='created', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, choices=[('saspay', 'SASPAY'), ('whatsapp', 'WhatsApp')], max_length=20, null=True, verbose_name='Méthode de paiement')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant figé au moment de la création.', max_digits=10, verbose_name='Montant total')),
                ('currency', models.CharField(default='USD', editable=False, max_length=3, verbose_name='Devise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmée le')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Annulée le')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='conference.conference', verbose_name='Conférence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'conference', 'status'], name='reservation_user_id_c1456f_idx'), models.Index(fields=['reference'], name='reservation_referen_a4f164_idx'), models.Index(fields=['status'], name='reservation_status_f1a03a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['created', 'payment_pending', 'payment_confirmed', 'confirmed', 'ticket_generated', 'present'])), fields=('user', 'conference'), name='unique_active_reservation_per_user')],
            },
        ),
    ]
