# Generated by Django 6.1.1 on 2026-10-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reference',
            field=models.CharField(db_index=True, help_text='Format : BGA-2026-XXXXXXX (généré automatiquement si vide).', max_length=20, unique=True, verbose_name='Référence'),
        ),
    ]
