# Generated by Django 6.1.1 on 2026-10-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='saspay_network',
            field=models.CharField(blank=True, choices=[('vodacom_cd_usd', 'Vodacom Congo (USD)'), ('airtel_cd_usd', 'Airtel Congo (USD)'), ('orange_cd_usd', 'Orange Congo (USD)')], help_text='Réseau mobile money pour le paiement SASPAY (USD).', max_length=30, verbose_name='Réseau SASPAY'),
        ),
    ]
