# Generated by Django 6.1.1 on 2026-10-05 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_saspay_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_phone_number',
            field=models.CharField(blank=True, help_text='Numéro mobile money qui recevra la demande de paiement. Par défaut : votre numéro WhatsApp.', max_length=20, validators=[django.core.validators.RegexValidator(message='Format international requis (ex: +243812345678).', regex='^\\+?[0-9]{9,15}$')], verbose_name='Numéro à débiter'),
        ),
    ]
