# Generated by Django 6.1.1 on 2026-10-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_payment_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='unique_active_reservation_per_user',
        ),
    ]
