# Generated by Django 6.1.1 on 2026-10-02 13:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ex: L'entrepreneuriat des jeunes à Kinshasa, Mythe ou Réalité ?", max_length=255, verbose_name='Titre')),
                ('title_fr', models.CharField(help_text="Ex: L'entrepreneuriat des jeunes à Kinshasa, Mythe ou Réalité ?", max_length=255, null=True, verbose_name='Titre')),
                ('title_en', models.CharField(help_text="Ex: L'entrepreneuriat des jeunes à Kinshasa, Mythe ou Réalité ?", max_length=255, null=True, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, help_text='Généré automatiquement depuis le titre si laissé vide.', max_length=280, unique=True, verbose_name='Slug URL')),
                ('organization_name', models.CharField(default="Bantondo's Génération ASBL", max_length=200, verbose_name="Nom de l'organisation")),
                ('date', models.DateTimeField(help_text='Ex: 27 novembre 2026 à 14h00', verbose_name='Date et heure')),
                ('location', models.CharField(help_text='Ex: Auditorium du CHESD GOMBE', max_length=255, verbose_name='Lieu')),
                ('location_fr', models.CharField(help_text='Ex: Auditorium du CHESD GOMBE', max_length=255, null=True, verbose_name='Lieu')),
                ('location_en', models.CharField(help_text='Ex: Auditorium du CHESD GOMBE', max_length=255, null=True, verbose_name='Lieu')),
                ('description', models.TextField(blank=True, default='À compléter', verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, default='À compléter', null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, default='À compléter', null=True, verbose_name='Description')),
                ('objective', models.TextField(blank=True, default='À compléter', verbose_name='Objectif')),
                ('objective_fr', models.TextField(blank=True, default='À compléter', null=True, verbose_name='Objectif')),
                ('objective_en', models.TextField(blank=True, default='À compléter', null=True, verbose_name='Objectif')),
                ('practical_info', models.TextField(blank=True, default='À compléter', verbose_name='Informations pratiques')),
                ('practical_info_fr', models.TextField(blank=True, default='À compléter', null=True, verbose_name='Informations pratiques')),
                ('practical_info_en', models.TextField(blank=True, default='À compléter', null=True, verbose_name='Informations pratiques')),
                ('is_free', models.BooleanField(default=False, help_text='Décocher pour une conférence payante.', verbose_name='Gratuit')),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=Decimal('5.70'), help_text='Montant en USD par place.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix par place')),
                ('currency', models.CharField(default='USD', editable=False, help_text='USD uniquement (décision du projet).', max_length=3, verbose_name='Devise')),
                ('total_seats', models.PositiveIntegerField(default=0, help_text='Laisser à 0 si la capacité est illimitée.', verbose_name='Nombre total de places')),
                ('is_active', models.BooleanField(default=False, help_text='Une seule conférence peut être active à la fois. Activer celle-ci désactivera automatiquement les autres.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
            ],
            options={
                'verbose_name': 'Conférence',
                'verbose_name_plural': 'Conférences',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_conference')],
            },
        ),
    ]
