# Generated by Django 6.1.1 on 2026-10-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='poster',
            field=models.ImageField(blank=True, help_text='Affiche officielle (JPG, PNG). Format portrait recommandé.', null=True, upload_to='conference/posters/', verbose_name='Affiche de la conférence'),
        ),
        migrations.AddField(
            model_name='conference',
            name='speakers',
            field=models.JSONField(blank=True, default=list, help_text='Liste d\'intervenants au format JSON : [{"name": "Nom Prénom", "role": "Fonction", "photo": "conference/speakers/nom.jpg"}]', verbose_name='Intervenants'),
        ),
    ]
