# Generated by Django 6.1.1 on 2026-10-03 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_conference_poster_conference_speakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='speakers',
        ),
        migrations.AlterField(
            model_name='conference',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=3, verbose_name='Devise'),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Jean KABILA', max_length=150, verbose_name='Nom complet')),
                ('role', models.CharField(help_text='Ex: Entrepreneur social, Fondateur de XYZ', max_length=200, verbose_name='Fonction / Titre')),
                ('role_fr', models.CharField(help_text='Ex: Entrepreneur social, Fondateur de XYZ', max_length=200, null=True, verbose_name='Fonction / Titre')),
                ('role_en', models.CharField(help_text='Ex: Entrepreneur social, Fondateur de XYZ', max_length=200, null=True, verbose_name='Fonction / Titre')),
                ('bio', models.TextField(blank=True, help_text='Courte biographie (optionnelle).', verbose_name='Biographie')),
                ('bio_fr', models.TextField(blank=True, help_text='Courte biographie (optionnelle).', null=True, verbose_name='Biographie')),
                ('bio_en', models.TextField(blank=True, help_text='Courte biographie (optionnelle).', null=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, help_text='Format carré recommandé (min 400x400px).', null=True, upload_to='conference/speakers/%Y/%m/', verbose_name='Photo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Les plus petits nombres apparaissent en premier.', verbose_name="Ordre d'affichage")),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='conference.conference', verbose_name='Conférence')),
            ],
            options={
                'verbose_name': 'Intervenant',
                'verbose_name_plural': 'Intervenants',
                'ordering': ['order', 'name'],
            },
        ),
    ]
