# Generated by Django 6.1.1 on 2026-10-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0003_remove_conference_speakers_alter_conference_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='contact_address',
            field=models.CharField(blank=True, help_text='Ex: Avenue X, Gombe, Kinshasa', max_length=255, verbose_name='Adresse physique'),
        ),
        migrations.AddField(
            model_name='conference',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Ex: contact@bantondos.cd', max_length=254, verbose_name='Email de contact'),
        ),
        migrations.AddField(
            model_name='conference',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Ex: +243986698720', max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='conference',
            name='social_facebook',
            field=models.URLField(blank=True, help_text='URL complète : https://facebook.com/...', verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='conference',
            name='social_instagram',
            field=models.URLField(blank=True, help_text='URL complète : https://instagram.com/...', verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='conference',
            name='social_linkedin',
            field=models.URLField(blank=True, help_text='URL complète : https://linkedin.com/...', verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='conference',
            name='social_tiktok',
            field=models.URLField(blank=True, help_text='URL complète : https://tiktok.com/@...', verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='conference',
            name='social_twitter',
            field=models.URLField(blank=True, help_text='URL complète : https://x.com/...', verbose_name='X (Twitter)'),
        ),
        migrations.AddField(
            model_name='conference',
            name='social_youtube',
            field=models.URLField(blank=True, help_text='URL complète : https://youtube.com/...', verbose_name='YouTube'),
        ),
    ]
