# Generated by Django 6.1.1 on 2026-10-02 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_reference', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Référence billet')),
                ('qr_token', models.CharField(db_index=True, help_text='Token HMAC signé, sans données personnelles.', max_length=64, unique=True, verbose_name='Token QR')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='tickets/qr/%Y/%m/', verbose_name='Image QR')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='tickets/pdf/%Y/%m/', verbose_name='Fichier PDF')),
                ('status', models.CharField(choices=[('generated', 'Généré'), ('used', 'Utilisé'), ('cancelled', 'Annulé')], db_index=True, default='generated', max_length=20, verbose_name='Statut')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Contrôlé par')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='reservations.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Billet',
                'verbose_name_plural': 'Billets',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['ticket_reference'], name='tickets_tic_ticket__e493bd_idx'), models.Index(fields=['qr_token'], name='tickets_tic_qr_toke_ba3ddf_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx')],
            },
        ),
    ]
