# Generated by Django 6.1.1 on 2026-10-02 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_reference'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['reservation', 'seat_number'], 'verbose_name': 'Billet', 'verbose_name_plural': 'Billets'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat_number',
            field=models.PositiveIntegerField(default=1, help_text='Position dans la réservation (1 à N).', verbose_name='Numéro de place'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/pdf/%Y/%m/', verbose_name='Fichier PDF individuel'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_reference',
            field=models.CharField(db_index=True, help_text='Format : BGA-2026-XXXXXXX-01', max_length=25, unique=True, verbose_name='Référence billet'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('reservation', 'seat_number'), name='unique_seat_per_reservation'),
        ),
    ]
